import React, { createContext, useContext, useState, useEffect } from 'react';
import { toast } from 'sonner';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  formatNumber: (num: number) => string;
  formatCurrency: (amount: number, unit?: '€/h' | '€/Monat') => string;
  formatDate: (date: Date | string, format?: 'short' | 'long') => string;
}

export const translations: Record<Language, Record<string, string>> = {
  de: {
    'nav.home': 'Startseite',
    'nav.search': 'Suche',
    'nav.saved': 'Gespeichert',
    'nav.applications': 'Bewerbungen',
    'nav.admin': 'Admin',
    'nav.employer': 'Arbeitgeber',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    
    // Menu
    'menu.browse': 'Entdecken',
    'menu.home': 'Startseite',
    'menu.my_pflegeflix': 'Mein Pflegeflix',
    'menu.dashboard': 'Dashboard',
    'menu.for_you': 'Für Dich',
    'menu.career': 'Meine Karriere',
    'menu.saved_jobs': 'Gespeicherte Jobs',
    'menu.applications': 'Bewerbungen',
    'menu.account_settings': 'Kontoeinstellungen',
    'menu.categories': 'Kategorien',
    'menu.post_job': 'Job veröffentlichen',
    'menu.my_jobs': 'Meine Jobs',
    'menu.applicants': 'Bewerber/innen',
    'menu.settings': 'Einstellungen',
    'menu.moderation': 'Moderation',
    'menu.data_view': 'Datenansicht',
    'menu.legal_settings': 'Rechtliche Einstellungen',
    'menu.language': 'Sprache',
    'menu.legal': 'Rechtliches',
    'menu.switch_role': 'Rolle wechseln',
    'menu.sign_out': 'Abmelden',
    'menu.sign_in': 'Anmelden',
    'menu.sign_up': 'Registrieren',
    'menu.close': 'Menü schließen',
    
    // Footer
    'footer.impressum': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.cookies': 'Cookie-Richtlinie',
    
    // Auth
    'auth.switching_role': 'Rolle wird gewechselt...',
    'auth.switch_role': 'Rolle wechseln',
    'auth.confirm_password': 'Passwort bestätigen',
    'auth.passwords_match': 'Passwörter stimmen überein',
    'auth.passwords_no_match': 'Passwörter stimmen nicht überein',
    'auth.success.account_created': 'Konto erfolgreich erstellt! Bitte bestätigen Sie Ihre E-Mail-Adresse.',
    'auth.error.title': 'Anmeldefehler',
    'auth.error.invalid_credentials': 'Ungültige Anmeldeinformationen. Bitte überprüfen Sie Ihre E-Mail und Ihr Passwort.',
    'auth.error.email_not_confirmed': 'Ihre E-Mail-Adresse ist noch nicht bestätigt. Bitte überprüfen Sie Ihren Posteingang.',
    'auth.error.too_many_requests': 'Zu viele Anmeldeversuche. Bitte versuchen Sie es später erneut.',
    'auth.error.network': 'Netzwerkfehler. Bitte überprüfen Sie Ihre Internetverbindung.',
    'auth.error.generic': 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'auth.error.try_again': 'Erneut versuchen',
    'auth.error.reset_password': 'Passwort zurücksetzen',
    'auth.error.create_account': 'Konto erstellen',
    'auth.password.hide': 'Passwort ausblenden',
    'auth.password.show': 'Passwort anzeigen',
    'auth.password.visible': 'Passwort ist sichtbar',
    'auth.password.hidden': 'Passwort ist ausgeblendet',
    'auth.login_required.title': 'Anmeldung erforderlich',
    'auth.login_required.message': 'Bitte melden Sie sich an oder registrieren Sie sich, um diese Funktion zu nutzen.',
    'auth.login_required.save_hint': 'Anmelden zum Speichern',
    
    // Employer Portal
    'employer.portal_title': 'Arbeitgeber-Portal',
    'employer.portal_subtitle': 'Verwalte deine Jobs und Bewerbungen',
    'employer.my_jobs': 'Meine Jobs',
    'employer.post_job': 'Job veröffentlichen',
    'employer.applicants': 'Bewerber/innen',
    'employer.settings': 'Einstellungen',
    'employer.settings_page_title': 'Einstellungen',
    'employer.settings_page_description': 'Verwalte deine Arbeitgeber-Einstellungen und Vorlagen',
    'employer.settings_page_subtitle': 'Passe deine Einstellungen an',
    'employer.message_templates': 'Nachrichtenvorlagen',
    
    // Categories
    'category.clinics': 'Kliniken',
    'category.hospital': 'Krankenhaus',
    'category.hospitals': 'Krankenhäuser',
    'category.nursing_homes': 'Altenheime',
    'category.intensive_care': 'Intensivpflege',
    'category.section': 'Kategorien',
    'category.back': 'Zurück',
    'category.edit_order': 'Reihenfolge bearbeiten',
    'category.done': 'Fertig',
    
    // Dashboard
    'dashboard.my_jobs': 'Meine Jobs',
    'dashboard.jobs_total': 'Jobs insgesamt',
    'dashboard.export': 'Exportieren',
    'dashboard.search_placeholder': 'Jobs durchsuchen...',
    'dashboard.copy': 'Kopie',
    'dashboard.empty.title': 'Noch keine Jobs',
    'dashboard.empty.description': 'Veröffentliche deine erste Stelle und erreiche qualifizierte Pflegekräfte.',
    'dashboard.empty.cta': 'Erste Stelle veröffentlichen',
    'dashboard.filter.all_status': 'Alle Status',
    'dashboard.filter.all_categories': 'Alle Kategorien',
    'dashboard.filter.draft': 'Entwurf',
    'dashboard.filter.online': 'Aktiv',
    'dashboard.filter.paused': 'Pausiert',
    'dashboard.filter.closed': 'Geschlossen',
    'dashboard.filter.expired': 'Abgelaufen',
    'dashboard.sort.newest': 'Neueste',
    'dashboard.sort.applications': 'Meiste Bewerbungen',
    'dashboard.sort.views': 'Meiste Aufrufe',
    'dashboard.status.draft': 'Entwurf',
    'dashboard.status.online': 'Aktiv',
    'dashboard.status.paused': 'Pausiert',
    'dashboard.status.closed': 'Geschlossen',
    'dashboard.status.expired': 'Abgelaufen',
    'dashboard.table.title': 'Titel',
    'dashboard.table.location': 'Standort',
    'dashboard.table.status': 'Status',
    'dashboard.table.views': 'Aufrufe',
    'dashboard.table.applications': 'Bewerbungen',
    'dashboard.table.metrics': 'Metriken',
    'dashboard.table.saved': 'Gespeichert',
    'dashboard.table.updated': 'Aktualisiert',
    'dashboard.table.actions': 'Aktionen',
    'dashboard.job.closed': 'Job erfolgreich geschlossen',
    'dashboard.bulk.selected': 'ausgewählt',
    'dashboard.bulk.pause': 'Pausieren',
    'dashboard.bulk.resume': 'Fortsetzen',
    'dashboard.bulk.close': 'Schließen',
    'dashboard.bulk.delete': 'Löschen',
    'dashboard.bulk.pause_success': 'Jobs pausiert',
    'dashboard.bulk.resume_success': 'Jobs aktiviert',
    'dashboard.bulk.close_success': 'Jobs geschlossen',
    'dashboard.bulk.delete_success': 'Jobs gelöscht',
    'dashboard.bulk.delete_confirm': 'Möchtest du die ausgewählten Jobs wirklich löschen?',
    'dashboard.action.preview': 'Vorschau',
    'dashboard.action.edit': 'Bearbeiten',
    'dashboard.action.pause': 'Pausieren',
    'dashboard.action.resume': 'Fortsetzen',
    'dashboard.action.delete': 'Löschen',
    'dashboard.welcome': 'Willkommen',
    'dashboard.user': 'Benutzer',
    'dashboard.manage_profile_applications': 'Verwalten Sie Ihr Profil und Ihre Bewerbungen',
    'dashboard.saved_jobs': 'Gespeicherte Jobs',
    'dashboard.applications': 'Bewerbungen',
    'dashboard.saved_searches': 'Gespeicherte Suchen',
    'dashboard.coming_soon': 'Bald verfügbar',
    'dashboard.overview': 'Übersicht',
    'dashboard.profile': 'Profil',
    'dashboard.recent_applications': 'Neueste Bewerbungen',
    'dashboard.last_5_applications': 'Ihre letzten 5 Bewerbungen',
    'dashboard.no_applications_yet': 'Keine Bewerbungen vorhanden',
    'dashboard.profile_summary': 'Profil-Übersicht',
    'dashboard.profile_data': 'Ihre Profildaten',
    'dashboard.name': 'Name',
    'dashboard.not_specified': 'Nicht angegeben',
    'dashboard.email': 'E-Mail',
    'dashboard.location': 'Standort',
    'dashboard.skills': 'Fähigkeiten',
    'dashboard.no_skills_specified': 'Keine angegeben',
    'dashboard.edit_profile': 'Profil bearbeiten',
    'dashboard.edit_profile_title': 'Profil bearbeiten',
    'dashboard.update_profile_info': 'Aktualisieren Sie Ihre persönlichen Informationen und Fähigkeiten',
    'dashboard.email_cannot_be_changed': 'E-Mail kann nicht geändert werden',
    'dashboard.city': 'Stadt',
    'dashboard.state': 'Bundesland',
    'dashboard.add_skill_placeholder': 'z.B. Intensivpflege, Wundmanagement',
    'dashboard.add': 'Hinzufügen',
    'dashboard.save_changes': 'Änderungen speichern',
    'dashboard.saving': 'Wird gespeichert...',
    'dashboard.privacy_settings': 'Datenschutzeinstellungen',
    'dashboard.jobs_for_later': 'Jobs, die Sie für später gespeichert haben',
    'dashboard.no_saved_jobs': 'Keine gespeicherten Jobs',
    'dashboard.no_saved_jobs_description': 'Sie haben noch keine Jobs gespeichert. Durchsuchen Sie Stellenangebote und speichern Sie interessante Jobs.',
    'dashboard.browse_jobs': 'Jobs durchsuchen',
    'dashboard.all_applications_overview': 'Übersicht über alle Ihre Bewerbungen',
    'dashboard.no_applications_description': 'Sie haben sich noch nicht auf Jobs beworben. Finden Sie passende Stellen und bewerben Sie sich noch heute!',
    'dashboard.applied_on': 'Beworben',
    'dashboard.cover_letter_short': 'Anschreiben',
    'dashboard.stage.submitted': 'Eingereicht',
    'dashboard.stage.viewed': 'Gesichtet',
    'dashboard.stage.interview': 'Vorstellungsgespräch',
    'dashboard.stage.offer': 'Angebot',
    'dashboard.stage.rejected': 'Abgelehnt',
    'dashboard.application.stage_updated': 'Bewerbungsstufe aktualisiert',
    'dashboard.application.notes_saved': 'Notizen gespeichert',
    'dashboard.application.move_to': 'Verschieben nach',
    'dashboard.application.cover_letter': 'Anschreiben',
    'dashboard.application.notes': 'Notizen',
    'dashboard.application.notes_placeholder': 'Füge private Notizen zu diesem Bewerber hinzu...',
    
    // Applicants
    'applicants.title': 'Bewerber/innen',
    'applicants.subtitle': 'Verwalte alle eingehenden Bewerbungen',
    'applicants.empty_title': 'Noch keine Bewerbungen',
    'applicants.empty_description': 'Noch keine Bewerbungen – veröffentliche deine erste Stelle.',
    'applicants.empty_action': 'Job veröffentlichen',
    'applicants.exported': 'Bewerbungen exportiert',
    'applicants.export': 'Exportieren',
    'applicants.all': 'Alle Bewerbungen',
    'applicants.by_job': 'Nach Stelle',
    'applicants.search_placeholder': 'Bewerbende suchen…',
    'applicants.all_stages': 'Alle Stufen',
    'applicants.submitted': 'Eingereicht',
    'applicants.viewed': 'Gesehen',
    'applicants.interview': 'Interview',
    'applicants.offer': 'Angebot',
    'applicants.rejected': 'Abgelehnt',
    'applicants.select_job_hint': 'Wähle eine Stelle, um Bewerbungen zu sehen.',
    'applicants.filter_stage': 'Stufe filtern',
    'applicants.filter_job': 'Stelle filtern',
    'applicants.all_jobs': 'Alle Stellen',
    'applicants.selected': 'ausgewählt',
    'applicants.change_stage': 'Stufe ändern',
    'applicants.delete_selected': 'Ausgewählte löschen',
    'applicants.applicant': 'Bewerber/in',
    'applicants.job': 'Stelle',
    'applicants.stage': 'Stufe',
    'applicants.rating': 'Bewertung',
    'applicants.applied': 'Beworben',
    'applicants.actions': 'Aktionen',
    'applicants.total': 'Gesamt',
    'applicants.bulk_deleted': 'Bewerbungen gelöscht',
    'applicants.bulk_updated': 'Bewerbungen aktualisiert',
    'applicants.view': 'Ansehen',
    'applicants.no_results': 'Keine Ergebnisse gefunden',
    'applicants.no_results_description': 'Versuche, deine Filter anzupassen oder die Suche zurückzusetzen.',
    'applicants.clear_filters': 'Filter zurücksetzen',
    'applicants.applied_for': 'Beworben für',
    'applicants.pipeline_stage': 'Pipeline-Stufe',
    'applicants.cover_letter': 'Anschreiben',
    'applicants.internal_notes': 'Interne Notizen',
    'applicants.notes_placeholder': 'Füge private Notizen zu diesem Bewerber hinzu...',
    'applicants.save_notes': 'Notizen speichern',
    'applicants.tags': 'Tags',
    'applicants.add_tag': 'Tag hinzufügen...',
    'applicants.add': 'Hinzufügen',
    'applicants.messages': 'Nachrichten',
    'applicants.message_placeholder': 'Nachricht an Bewerber senden...',
    'applicants.message_sent': 'Nachricht gesendet',
    'applicants.activity': 'Aktivität',
    'applicants.system': 'System',
    'applicants.changed_stage_from': 'hat die Stufe geändert von',
    'applicants.to': 'zu',
    'applicants.you': 'Sie',
    'applicants.stage_updated': 'Stufe aktualisiert',
    'applicants.rating_updated': 'Bewertung aktualisiert',
    'applicants.recommend': 'Empfehlen',
    'applicants.recommend_updated': 'Empfehlung aktualisiert',
    'applicants.delete_confirm': 'Möchtest du diesen Bewerber wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'applicants.deleted': 'Bewerber gelöscht',
    
    // Saved Searches
    'saved_searches.title': 'Gespeicherte Suchen',
    'saved_searches.subtitle': 'Verwalte deine gespeicherten Filter und E-Mail-Benachrichtigungen.',
    'saved_searches.empty_title': 'Noch keine gespeicherten Suchen',
    'saved_searches.empty_description': 'Speichere eine Suche, um E-Mail-Benachrichtigungen zu erhalten, sobald passende Jobs erscheinen.',
    'saved_searches.empty_action': 'Erste Suche speichern',
    'saved_searches.filters_applied': 'Filter',
    'saved_searches.email_alerts': 'E-Mail-Benachrichtigungen',
    'saved_searches.alert_none': 'Keine',
    'saved_searches.alert_daily': 'Täglich',
    'saved_searches.alert_weekly': 'Wöchentlich',
    'saved_searches.view_results': 'Ergebnisse ansehen',
    'saved_searches.delete': 'Suche löschen',
    'saved_searches.delete_confirm': 'Möchtest du diese gespeicherte Suche wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'saved_searches.deleted': 'Suche gelöscht',
    'saved_searches.updated': 'Suche aktualisiert',
    'saved_searches.rename': 'Suche umbenennen',
    'saved_searches.search_name': 'Suchname',
    'saved_searches.search_name_placeholder': 'z. B. „Krankenpflege Berlin"',
    'saved_searches.unsubscribe_success': 'E-Mail-Benachrichtigungen wurden deaktiviert',
    'saved_searches.unsubscribe_hint': 'Sie können sich jederzeit über den Link in der E-Mail abmelden',
    
    // Favorites (Saved Jobs)
    'favorites.title': 'Gespeicherte Jobs',
    'favorites.removed': 'Job aus Favoriten entfernt',
    'favorites.saved': 'Job gespeichert',
    'favorites.description': 'Verwalten Sie Ihre gespeicherten Jobs für später',

    // Footer
    'footer.company_info': 'Unternehmensangaben',
    'footer.legal': 'Rechtliches',
    'footer.support': 'Datenschutz & Support',
    'footer.employers': 'Für Arbeitgeber',
    'footer.privacy_center': 'Datenschutzcenter',
    'footer.candidate_privacy': 'Bewerber-Datenschutz',
    'footer.cookie_settings': 'Cookie-Einstellungen',
    'footer.dpa': 'Auftragsverarbeitung (AVV)',
    'footer.post_job': 'Job veröffentlichen',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.company_address': 'Pflegeflix GmbH, Musterstraße 123, 10115 Berlin, Deutschland',
    'footer.accessibility': 'Barrierefreiheit',
    
    // Job posting
    'job.published_success': 'Job erfolgreich veröffentlicht',
    'job.publish_success.title': 'Job erfolgreich veröffentlicht!',
    'job.publish_success.description': 'Ihre Stellenanzeige ist jetzt live und für Kandidaten sichtbar.',
    'job.publish_success.view_my_jobs': 'Meine Jobs ansehen',
    'job.publish_success.view_posting': 'Stellenanzeige ansehen',
    'job.publish_success.post_another': 'Weitere Stelle veröffentlichen',
    'job.no_slots.title': 'Keine freien Stellenanzeigen-Slots',
    'job.no_slots.description': 'Sie haben Ihr Stellenanzeigen-Limit für Ihr aktuelles Abo erreicht.',
    'job.no_slots.upgrade': 'Abo upgraden',
    'job.no_slots.manage_jobs': 'Bestehende Jobs verwalten',
    'job.draft_saved': 'Entwurf gespeichert',
    'job.delete_confirm': 'Möchtest du diesen Job wirklich löschen?',
    'job.step1.title': 'Schritt 1 – Grunddaten',
    'job.field.title': 'Jobtitel',
    'job.field.title_placeholder': 'z. B. Pflegefachkraft',
    'job.field.category': 'Kategorie',
    'job.field.category_placeholder': 'Kategorie wählen',
    'job.field.city': 'Stadt',
    'job.field.city_placeholder': 'Stadt wählen',
    'job.field.state': 'Bundesland',
    'job.field.state_placeholder': 'Bundesland wählen',
    'job.post.back': 'Zurück',
    'job.post.save_draft': 'Entwurf speichern',
    'job.post.next': 'Weiter',
    'job.toast.paused': 'Job pausiert',
    'job.toast.activated': 'Job aktiviert',
    'job.toast.deleted': 'Job gelöscht',
    'job.new': 'Neu',
    'job.apply': 'Jetzt bewerben',
    'job.days_ago': 'Vor {days} Tagen',
    'job.field.description': 'Beschreibung',
    'job.field.description_placeholder': 'Beschreiben Sie die Aufgaben und Verantwortlichkeiten...',
    'job.field.requirements': 'Anforderungen',
    'job.field.requirement_placeholder': 'z.B. Abgeschlossene Ausbildung als Pflegefachkraft',
    'job.field.add_requirement': 'Anforderung hinzufügen',
    'job.field.specialties': 'Fachbereiche',
    'job.field.shift_type': 'Schichttyp',
    'job.field.shift_placeholder': 'z.B. Tagschicht, Nachtschicht, Wechselschicht',
    'job.step2.title': 'Schritt 2 – Details',
    'job.step3.title': 'Schritt 3 – Vergütung',
    'job.field.salary_min': 'Mindestgehalt',
    'job.field.salary_max': 'Maximalgehalt',
    'job.field.salary_unit': 'Gehaltseinheit',
    'job.field.salary_unit_placeholder': 'Einheit wählen',
    'job.field.contract_type': 'Vertragstyp',
    'job.field.contract_placeholder': 'Vertragstyp wählen',
    'job.field.featured': 'Hervorgehoben',
    'job.field.featured_desc': 'Stellenanzeige prominent auf der Startseite platzieren',
    'job.step4.title': 'Schritt 4 – Bewerbung',
    'job.field.application_method': 'Bewerbungsmethode',
    'job.field.application_email': 'Per E-Mail bewerben',
    'job.field.application_external': 'Externer Link',
    'job.field.email': 'E-Mail',
    'job.field.url': 'URL',
    'job.field.auto_reply': 'Automatische Antwort',
    'job.field.auto_reply_placeholder': 'Optional: Nachricht, die Bewerber nach dem Absenden erhalten',
    'job.field.contact_person': 'Ansprechpartner',
    'job.field.contact_placeholder': 'Optional: Name des Ansprechpartners für Bewerbungen',
    'job.step5.title': 'Schritt 5 – Vorschau & Veröffentlichen',
    'job.post.step': 'Schritt',
    'job.post.of': 'von',
    'job.post.publish': 'Job veröffentlichen',
    'job.apply_for_position': 'Für diese Position bewerben',
    'job.at_facility': 'bei',
    'job.default_facility': 'einer Einrichtung',
    'job.competitive_salary': 'Wettbewerbsfähiges Gehalt',
    'job.apply_now_description': 'Bewerben Sie sich jetzt auf diese Stelle.',
    'job.remove_from_saved': 'Aus Favoriten entfernen',
    'job.save_job': 'Job speichern',
    'job.view_details_for': 'Details ansehen für {title} in {city}, {state}',
    'job.posted_days_ago': 'Vor {days} Tagen veröffentlicht',
    'job.tags_label': 'Tags',
    'job.salary_range_label': 'Gehaltsspanne: {salary_min} bis {salary_max} {salary_unit}',
    'job.by_agreement': 'Nach Vereinbarung',
    'job.contract_shift_label': 'Vertragstyp: {contract_type}, Schichttyp: {shift_type}',
    'job.salary_label': 'Gehalt',
    'job.contract_label': 'Vertrag',
    'job.shift_label': 'Schicht',
    'job.description_heading': 'Jobbeschreibung',
    'job.requirements_heading': 'Anforderungen',
    'job.bonus_heading': 'Boni',
    
    // Application
    'application.cover_letter': 'Bewerbungsschreiben (optional)',
    'application.success': 'Bewerbung erfolgreich eingereicht!',
    'application.inbox_title': 'Bewerbungen',
    'application.select_app_message': 'Wählen Sie eine Bewerbung aus, um Nachrichten zu sehen',
    'application.message_input_placeholder': 'Nachricht eingeben...',
    'application.message_sent_toast': 'Nachricht gesendet',
    'application.send_message': 'Nachricht senden',
    'application.error_sending_message': 'Fehler beim Senden',
    'application.submitting': 'Wird gesendet...',
    'applications.description': 'Verwalten Sie Ihre Bewerbungen und kommunizieren Sie mit Arbeitgebern.',
    'applications.subtitle': 'Ihre Übersicht über alle Bewerbungen und Nachrichten',
    'applications.title_short': 'Bewerbungen',
    
    // Carousels
    'carousel.recommended': 'Empfohlen',
    'carousel.clinics': 'Kliniken & Krankenhäuser',
    'carousel.nursing_homes': 'Altenheime',
    'carousel.one_on_one': '1:1 Intensivpflege',
    'carousel.night_part': 'Nachtschicht-Empfehlungen',
    'carousel.for_you': 'Für dich',
    
    // Hero
    'hero.title': 'Dein Traumjob in der Pflege',
    'hero.subtitle': 'Entdecke Tausende Stellen in ganz Deutschland',
    
    // Message Templates
    'templates.title': 'Nachrichtenvorlagen',
    'templates.new': 'Neue Vorlage',
    'templates.edit': 'Bearbeiten',
    'templates.delete': 'Löschen',
    'templates.delete_confirm': 'Möchtest du diese Vorlage wirklich löschen?',
    'templates.deleted': 'Vorlage gelöscht',
    'templates.saved': 'Vorlage gespeichert',
    'templates.empty_title': 'Noch keine Vorlagen',
    'templates.empty_description': 'Erstelle Vorlagen für häufig verwendete Nachrichten.',
    'templates.empty_action': 'Erste Vorlage erstellen',
    'templates.name': 'Name',
    'templates.subject': 'Betreff',
    'templates.body': 'Nachricht',
    'templates.type': 'Typ',
    'templates.type_general': 'Allgemein',
    'templates.type_interview': 'Einladung zum Gespräch',
    'templates.type_offer': 'Stellenangebot',
    'templates.type_rejection': 'Absage',
    'templates.use_template': 'Vorlage verwenden...',
    'templates.fill_all_fields': 'Bitte alle Pflichtfelder ausfüllen',
    'templates.error_saving': 'Fehler beim Speichern',
    
    // Common
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.confirm': 'Bestätigen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.refresh': 'Aktualisieren',
    'common.view': 'Ansehen',
    'common.no_results': 'Keine Ergebnisse',
    'common.view_results': 'Ergebnisse ansehen',
    'common.rename': 'Umbenennen',
    'common.rename_search': 'Suche umbenennen',
    'common.rename_description': 'Gib einen neuen Namen für diese Suche ein.',
    'common.delete_search': 'Suche löschen?',
    'common.delete_search_description': 'Diese Aktion kann nicht rückgängig gemacht werden. Die Suche und alle zugehörigen E-Mail-Benachrichtigungen werden gelöscht.',
    'common.name': 'Name',
    'common.created': 'Erstellt am',
    'common.never': 'Nie',
    'common.daily': 'Täglich',
    'common.weekly': 'Wöchentlich',
    'loading': 'Laden...',
    'search.filters': 'Filter',
    'privacy_center.delete_cancel': 'Abbrechen',
    'cancel': 'Abbrechen',
    'common.download_pdf': 'Als PDF herunterladen',
    'common.remove_item': '{item} entfernen',
    
    // Errors
    'error.unauthorized': 'Keine Berechtigung',
    'error.load_failed': 'Laden fehlgeschlagen',
    'error.update_failed': 'Aktualisierung fehlgeschlagen',
    'error.delete_failed': 'Löschen fehlgeschlagen',
    'error.duplicate_failed': 'Duplizierung fehlgeschlagen',
    'error.generic': 'Ein Fehler ist aufgetreten',
    'error.page_not_found': 'Seite nicht gefunden',
    'error.page_not_found_description': 'Entschuldigung, diese Seite existiert nicht.',
    'navigation.go_back': 'Zurück',
    'navigation.to_search': 'Zur Jobsuche',
    'error.job_not_found': 'Job nicht gefunden',
    'error.job_not_found_description': 'Die von Ihnen gesuchte Stellenanzeige existiert nicht oder wurde entfernt.',
    'error.required_fields': 'Bitte füllen Sie alle Pflichtfelder aus.',
    'error.posting_limit_reached': 'Stellenanzeigen-Limit erreicht',
    'error.upgrade_subscription': 'Bitte upgraden Sie Ihr Abo, um weitere Jobs zu veröffentlichen.',
    'error.publish_failed': 'Veröffentlichung fehlgeschlagen',
    'error.page_not_found_seo_title': 'Seite nicht gefunden - 404',
    'dashboard.load_data_error': 'Fehler beim Laden der Dashboard-Daten.',
    'dashboard.profile_saved': 'Profil gespeichert',
    'dashboard.profile_saved_description': 'Ihre Profilinformationen wurden erfolgreich aktualisiert.',
    'error.save_failed': 'Speichern fehlgeschlagen',
    'dashboard.profile_save_error': 'Fehler beim Speichern Ihrer Profilinformationen.',
    
    // Filters (used in LocationFilter & FullScreenFilterSheet)
    'filter.location': 'Standort',
    'filter.search_cities': 'Stadt suchen…',
    'filter.remove_city': 'Stadt {city} entfernen',
    'filter.max_cities_reached': 'Maximal 3 Städte ausgewählt',
    'filter.city_helper': 'Wähle bis zu 3 Städte aus',
    'filter.close_menu': 'Filtermenü schließen',
    
    // Saved Searches dialog (Search page)
    'saved_searches.save_current': 'Aktuelle Suche speichern',
    
    // Favorites page description
    'favorites.description': 'Verwalten Sie Ihre gespeicherten Jobs für später',
    
    // Job posting / filters
    'job.field.facility_type': 'Einrichtungstyp',

    // StepDetails specialty tag translations (subcategory.*)
    'subcategory.intensivstation': 'Intensivstation',
    'subcategory.op_anästhesie': 'OP/Anästhesie',
    'subcategory.chirurgie': 'Chirurgie',
    'subcategory.internistik': 'Internistik',
    'subcategory.notaufnahme': 'Notaufnahme',
    'subcategory.dialyse': 'Dialyse',
    'subcategory.stationär': 'Stationär',
    'subcategory.kurzzeitpflege': 'Kurzzeitpflege',
    'subcategory.demenz': 'Demenz',
    'subcategory.gerontopsychiatrie': 'Gerontopsychiatrie',
    'subcategory.leitung': 'Leitung',
    'subcategory.beatmung': 'Beatmung',
    'subcategory.homecare': 'Homecare',
    'subcategory.kinder': 'Kinder',
    'subcategory.nacht': 'Nacht',
    'subcategory.24h': '24 h',

    // Optional nav labels (for consistency if used)
    'nav.for_you': 'Für Dich',
    'nav.career': 'Meine Karriere',

    // Legal Pages
    'legal.last_updated': 'Zuletzt aktualisiert',
    'legal.impressum.title': 'Impressum',
    'legal.impressum.provider': 'Dienstanbieter',
    'legal.impressum.contact': 'Kontakt',
    'legal.impressum.representative': 'Vertreten durch',
    'legal.impressum.register': 'Registereintrag',
    'legal.impressum.vat': 'Umsatzsteuer-ID',
    'legal.impressum.editorial': 'Redaktionell verantwortlich',
    'legal.impressum.dispute': 'Streitschlichtung',
    'legal.impressum.dispute_text': 'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:',
    'legal.candidate.title': 'Bewerber-Datenschutzhinweise',
    'legal.candidate.introduction': 'Einleitung',
    'legal.candidate.introduction_text': 'Diese Datenschutzhinweise erläutern, wie wir Ihre personenbezogenen Daten im Rahmen Ihrer Bewerbung über unsere Plattform verarbeiten.',
    'legal.candidate.joint_roles': 'Gemeinsame Verantwortlichkeit',
    'legal.candidate.joint_roles_text': 'Pflegeflix und der jeweilige Arbeitgeber sind gemeinsam für die Verarbeitung Ihrer Daten verantwortlich.',
    'legal.candidate.data_types': 'Arten der verarbeiteten Daten',
    'legal.candidate.data_types_text': 'Wir verarbeiten die Daten, die Sie uns im Rahmen Ihrer Bewerbung zur Verfügung stellen (z.B. Name, Kontaktdaten, Lebenslauf, Anschreiben).',
    'legal.candidate.purposes': 'Zwecke der Datenverarbeitung',
    'legal.candidate.purposes_text': 'Ihre Daten werden ausschließlich zur Abwicklung des Bewerbungsprozesses und zur Kontaktaufnahme durch den Arbeitgeber verwendet.',
    'legal.candidate.legal_basis': 'Rechtsgrundlage der Verarbeitung',
    'legal.candidate.legal_basis_text': 'Die Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO (Vertragsanbahnung) und Art. 6 Abs. 1 lit. a DSGVO (Ihre Einwilligung).',
    'legal.candidate.retention': 'Speicherdauer',
    'legal.candidate.retention_text': 'Ihre Daten werden für die Dauer des Bewerbungsprozesses und maximal 6 Monate danach gespeichert, sofern keine längere Einwilligung vorliegt.',
    'legal.candidate.recipients': 'Empfänger der Daten',
    'legal.candidate.recipients_text': 'Ihre Daten werden an den Arbeitgeber übermittelt, bei dem Sie sich bewerben.',
    'legal.candidate.rights': 'Ihre Rechte als betroffene Person',
    'legal.candidate.rights_text': 'Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch und Datenübertragbarkeit.',
    'legal.cookies.title': 'Cookie-Richtlinie',
    'legal.cookies.introduction': 'Einleitung',
    'legal.cookies.introduction_text': 'Diese Cookie-Richtlinie erklärt, wie Pflegeflix Cookies und ähnliche Technologien auf unserer Website verwendet.',
    'legal.cookies.what_are': 'Was sind Cookies?',
    'legal.cookies.what_are_text': 'Cookies sind kleine Textdateien, die von Websites auf Ihrem Gerät gespeichert werden, um Informationen zu speichern.',
    'legal.cookies.essential': 'Essenzielle Cookies',
    'legal.cookies.essential_text': 'Diese Cookies sind für die grundlegende Funktion der Website unerlässlich und können nicht deaktiviert werden.',
    'legal.cookies.analytics': 'Analyse-Cookies',
    'legal.cookies.analytics_text': 'Diese Cookies helfen uns zu verstehen, wie Besucher mit der Website interagieren, indem sie Informationen anonym sammeln und melden.',
    'legal.cookies.marketing': 'Marketing-Cookies',
    'legal.cookies.marketing_text': 'Diese Cookies werden verwendet, um Besuchern auf Websites zu folgen. Ziel ist es, Anzeigen zu schalten, die für den einzelnen Nutzer relevant und ansprechend sind.',
    'legal.cookies.manage': 'Ihre Cookie-Einstellungen verwalten',
    'legal.cookies.manage_text': 'Sie können Ihre Cookie-Einstellungen jederzeit anpassen:',
    'legal.cookies.withdrawal': 'Widerruf der Einwilligung',
    'legal.cookies.withdrawal_text': 'Sie können Ihre Einwilligung zur Verwendung von Cookies jederzeit widerrufen, indem Sie Ihre Einstellungen ändern.',
    'legal.cookies.third_party': 'Drittanbieter-Cookies',
    'legal.cookies.third_party_text': 'Wir verwenden auch Cookies von Drittanbietern, die von unseren Partnern gesetzt werden.',
    'legal.cookies.rights': 'Ihre Rechte',
    'legal.cookies.rights_text': 'Sie haben das Recht, Informationen über die von uns verwendeten Cookies anzufordern und deren Verwendung einzuschränken.',
    'legal.cookies.table.name': 'Name',
    'legal.cookies.table.provider': 'Anbieter',
    'legal.cookies.table.purpose': 'Zweck',
    'legal.cookies.table.duration': 'Dauer',
    'legal.cookies.table.basis': 'Rechtsgrundlage',
    'legal.cookies.ga_purpose': 'Registriert eine eindeutige ID, die verwendet wird, um statistische Daten darüber zu generieren, wie der Besucher die Website nutzt.',
    'legal.cookies.gid_purpose': 'Registriert eine eindeutige ID, die verwendet wird, um statistische Daten darüber zu generieren, wie der Besucher die Website nutzt.',
    'legal.cookies.fbp_purpose': 'Wird von Facebook verwendet, um eine Reihe von Werbeprodukten zu liefern, z. B. Echtzeitgebote von Drittanbietern.',
    'legal.cookies.24_months': '24 Monate',
    'legal.cookies.24_hours': '24 Stunden',
    'legal.cookies.90_days': '90 Tage',
    'legal.dpa.title': 'Datenschutz-Folgenabschätzung (DPA)',
    'legal.dpa.sign': 'DPA unterzeichnen',
    'legal.privacy.title': 'Datenschutzerklärung',
    'legal.privacy.controller': 'Name und Kontaktdaten des Verantwortlichen',
    'legal.privacy.controller_details': 'Pflegeflix GmbH\nMusterstraße 123\n10115 Berlin\nDeutschland\nE-Mail: datenschutz@pflegeflix.de',
    'legal.privacy.dpo': 'Kontaktdaten des Datenschutzbeauftragten',
    'legal.privacy.dpo_details': 'Ein Datenschutzbeauftragter ist nicht gesetzlich vorgeschrieben.',
    'legal.privacy.purposes': 'Zwecke und Rechtsgrundlagen der Verarbeitung',
    'legal.privacy.purpose_account': 'Kontoverwaltung und Jobvermittlung',
    'legal.privacy.purpose_account_text': 'Wir verarbeiten Ihre Daten zur Bereitstellung unserer Plattformdienste, zur Verwaltung Ihres Nutzerkontos und zur Vermittlung von Jobs. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung).',
    'legal.privacy.purpose_jobs': 'Veröffentlichung von Stellenanzeigen',
    'legal.privacy.purpose_jobs_text': 'Arbeitgeberdaten werden zur Veröffentlichung von Stellenanzeigen verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.',
    'legal.privacy.purpose_security': 'Sicherheit und Betrugsprävention',
    'legal.privacy.purpose_security_text': 'Zur Gewährleistung der Sicherheit unserer Systeme und zur Verhinderung von Betrug verarbeiten wir Zugriffsdaten. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse).',
    'legal.privacy.purpose_email': 'E-Mail-Kommunikation',
    'legal.privacy.purpose_email_text': 'Wir nutzen Ihre E-Mail-Adresse für die Kommunikation im Rahmen der Jobvermittlung und für Benachrichtigungen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO.',
    'legal.privacy.recipients': 'Empfänger oder Kategorien von Empfängern der personenbezogenen Daten',
    'legal.privacy.recipients_details': 'Ihre Daten werden an den jeweiligen Arbeitgeber übermittelt, bei dem Sie sich bewerben. Zudem nutzen wir Dienstleister für Hosting und E-Mail-Versand.',
    'legal.privacy.data_categories': 'Kategorien personenbezogener Daten',
    'legal.privacy.data_categories_details': 'Wir verarbeiten Stammdaten (Name, Adresse), Kontaktdaten (E-Mail, Telefon), Bewerbungsdaten (Lebenslauf, Anschreiben) und Nutzungsdaten (IP-Adresse, Zugriffszeiten).',
    'legal.privacy.transfers': 'Übermittlung von personenbezogenen Daten an ein Drittland',
    'legal.privacy.transfers_details': 'Eine Übermittlung an Drittländer außerhalb der EU/EWR findet nur statt, wenn dies zur Vertragserfüllung notwendig ist oder Sie eingewilligt haben.',
    'legal.privacy.retention': 'Dauer der Speicherung der personenbezogenen Daten',
    'legal.privacy.retention_details': 'Daten werden gelöscht, sobald sie für die Zwecke, für die sie erhoben wurden, nicht mehr erforderlich sind, oder Sie Ihre Einwilligung widerrufen.',
    'legal.privacy.rights': 'Ihre Rechte als betroffene Person',
    'legal.privacy.rights_details': 'Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch und Datenübertragbarkeit.',
    'legal.privacy.complaint': 'Beschwerderecht bei einer Aufsichtsbehörde',
    'legal.privacy.complaint_details': 'Sie haben das Recht, sich bei einer Datenschutzaufsichtsbehörde über die Verarbeitung Ihrer personenbezogenen Daten zu beschweren.',
    'legal.privacy.requirement': 'Erforderlichkeit der Bereitstellung personenbezogener Daten',
    'legal.privacy.requirement_details': 'Die Bereitstellung Ihrer Daten ist für die Nutzung unserer Dienste erforderlich. Ohne diese Daten können wir den Vertrag nicht erfüllen.',
    'legal.privacy.automated': 'Bestehen einer automatisierten Entscheidungsfindung',
    'legal.privacy.automated_details': 'Es findet keine automatisierte Entscheidungsfindung einschließlich Profiling statt.',

    // Search Page
    'search.title': 'Jobsuche',
    'search.description_base': 'Finde deinen nächsten Job in der Pflege.',
    'search.jobs_find': 'Jobs finden',
    'search.placeholder': 'Jobtitel, Ort, Stichwort...',
    'search.min_salary': 'Min: {value}€',
    'search.max_salary': 'Max: {value}€',
    'search.city_helper': 'Wähle bis zu 3 Städte aus',
    'search.max_cities_reached': 'Maximal 3 Städte ausgewählt',
    'search.search_cities': 'Stadt suchen…',
    'search.remove_city': 'Stadt {city} entfernen',
    'search.apply_filters': 'Filter anwenden',
    'search.clear': 'Zurücksetzen',
    'search.location': 'Standort',
    'search.top_specialties': 'Top (Empfohlen)',
    'search.other_specialties': 'Weitere',
    'search.no_specialties_found': 'Keine Fachbereiche gefunden',
    'search.show_more': 'Mehr anzeigen ({count})',
    'search.show_less': 'Weniger anzeigen',
    'search.active_filters': 'aktive Filter',
    'search.remove_filter': '{filter} entfernen',
    'search.min_salary_label': 'Mindestgehalt',
    'search.max_salary_label': 'Maximalgehalt',
    'search.posted_label': 'Veröffentlichung',
    'search.posted_options.24h': 'Letzte 24 Stunden',
    'search.posted_options.7d': 'Letzte 7 Tage',
    'search.posted_options.30d': 'Letzte 30 Tage',
    'search.no_info': 'Keine Angabe',
    'search.radius_around': 'Radius um {city}',
    'search.show_results': 'Ergebnisse anzeigen ({count})',
    'search.filter_options': 'Filteroptionen',
    'search.close_menu': 'Filtermenü schließen',
    'search.reset_all_filters': 'Alle Filter zurücksetzen',
    'search.search_specialties': 'Fachbereich suchen…',
    'search.selected_count': 'Ausgewählt ({count})',
    'search.no_jobs_found': 'Keine Jobs gefunden',
    'search.no_jobs_found_description': 'Versuche, deine Filter anzupassen oder die Suche zurückzusetzen.',
    'search.no_jobs_available': 'Keine Jobs verfügbar',
    'search.no_jobs_available_description': 'Derzeit sind keine Jobs verfügbar. Bitte versuchen Sie es später erneut oder passen Sie Ihre Suche an.',
    'search.reset_filters': 'Filter zurücksetzen',
    'search.results_region_label': 'Suchergebnisse',
    
    // Contract Types
    'contract.Vollzeit': 'Vollzeit',
    'contract.Teilzeit': 'Teilzeit',
    'contract.Minijob': 'Minijob',
    'contract.Befristet': 'Befristet',

    // Shift Types
    'shift_type.tagschicht': 'Tagschicht',
    'shift_type.nachtschicht': 'Nachtschicht',
    'shift_type.wechselschicht': 'Wechselschicht',
    'shift_type.bereitschaftsdienst': 'Bereitschaftsdienst',
    
    // Career Tools
    'career.title': 'Meine Karriere',
    'career.subtitle': 'Professionelle Tools für Ihre Bewerbung und Karriereplanung',
    'career.cv_builder_title': 'Lebenslauf-Builder',
    'career.cv_builder_description': 'Erstellen Sie einen professionellen Lebenslauf mit Vorlagen für das Gesundheitswesen',
    'career.cv_builder_cta': 'Lebenslauf erstellen',
    'career.cover_letter_ai_title': 'KI-Anschreiben',
    'career.cover_letter_ai_description': 'Generieren Sie maßgeschneiderte Anschreiben mit künstlicher Intelligenz',
    'career.cover_letter_ai_cta': 'Anschreiben generieren',
    'career.salary_planner_title': 'Gehaltsplaner',
    'career.salary_planner_description': 'Vergleichen Sie Gehaltsspannen nach Rolle, Erfahrung und Region',
    'career.salary_planner_cta': 'Gehalt vergleichen',
    'career.tip_title': '💡 Tipp',
    'career.tip_description': 'Nutzen Sie alle drei Tools, um Ihre Bewerbung optimal vorzubereiten. Ihr erstellter Lebenslauf kann direkt bei Bewerbungen verwendet werden!',

    // CV Builder
    'cv_builder.title': 'Lebenslauf-Builder',
    'cv_builder.save': 'Speichern',
    'cv_builder.saving': 'Wird gespeichert...',
    'cv_builder.download_pdf': 'Als PDF',
    'cv_builder.personal_info_title': 'Persönliche Informationen',
    'cv_builder.name': 'Name',
    'cv_builder.email': 'E-Mail',
    'cv_builder.phone': 'Telefon',
    'cv_builder.city': 'Stadt',
    'cv_builder.work_experience_title': 'Berufserfahrung',
    'cv_builder.add_experience': 'Hinzufügen',
    'cv_builder.position': 'Position',
    'cv_builder.job_title_placeholder': 'Jobtitel',
    'cv_builder.company_placeholder': 'Unternehmen',
    'cv_builder.start_date_placeholder': 'Startdatum',
    'cv_builder.end_date_placeholder': 'Enddatum',
    'cv_builder.description_placeholder': 'Beschreibung',
    'cv_builder.education_title': 'Ausbildung',
    'cv_builder.add_education': 'Hinzufügen',
    'cv_builder.degree_placeholder': 'Abschluss',
    'cv_builder.institution_placeholder': 'Institution',
    'cv_builder.year_placeholder': 'Jahr',
    'cv_builder.skills_title': 'Fähigkeiten',
    'cv_builder.skills_placeholder': 'Geben Sie Ihre Fähigkeiten ein (getrennt durch Kommas)',
    'cv_builder.toast.save_success': 'CV gespeichert!',
    'cv_builder.toast.save_error': 'Fehler beim Speichern des Lebenslaufs',
    'cv_builder.toast.pdf_soon': 'PDF-Export wird in Kürze verfügbar sein',

    // Cover Letter Generator
    'cover_letter.title': 'KI-Anschreiben Generator',
    'cover_letter.subtitle': 'Erstellen Sie ein professionelles, auf die Stelle zugeschnittenes Anschreiben',
    'cover_letter.job_details_title': 'Stellendetails',
    'cover_letter.job_title': 'Jobtitel *',
    'cover_letter.job_title_placeholder': 'z.B. Krankenpfleger/in',
    'cover_letter.company_name': 'Unternehmen / Einrichtung *',
    'cover_letter.company_name_placeholder': 'z.B. Universitätsklinikum Berlin',
    'cover_letter.facility_type': 'Einrichtungstyp (optional)',
    'cover_letter.facility_type_placeholder': 'z.B. Krankenhaus, Pflegeheim',
    'cover_letter.generate_cta': 'Anschreiben mit KI generieren',
    'cover_letter.generating': 'Wird generiert...',
    'cover_letter.toast.fill_fields': 'Bitte füllen Sie alle Pflichtfelder aus',
    'cover_letter.toast.generate_success': 'Anschreiben generiert!',
    'cover_letter.toast.generate_error': 'Fehler beim Generieren des Anschreibens',
    'cover_letter.your_cover_letter_title': 'Ihr Anschreiben',
    'cover_letter.copy': 'Kopieren',
    'cover_letter.download': 'Download',
    'cover_letter.toast.copy_success': 'In Zwischenablage kopiert!',
    'cover_letter.toast.download_success': 'Anschreiben heruntergeladen!',
    'cover_letter.edit_hint': 'Sie können den generierten Text bearbeiten, bevor Sie ihn verwenden.',

    // Salary Planner
    'salary_planner.title': 'Gehaltsplaner',
    'salary_planner.subtitle': 'Vergleichen Sie Gehaltsspannen basierend auf Rolle, Erfahrung und Region',
    'salary_planner.your_details_title': 'Ihre Angaben',
    'salary_planner.role': 'Berufsbezeichnung',
    'salary_planner.select_role_placeholder': 'Wählen Sie eine Rolle',
    'salary_planner.state': 'Bundesland',
    'salary_planner.select_state_placeholder': 'Wählen Sie ein Bundesland',
    'salary_planner.facility_type': 'Einrichtungstyp',
    'salary_planner.select_type_placeholder': 'Wählen Sie einen Typ',
    'salary_planner.experience_level': 'Erfahrungslevel',
    'salary_planner.select_level_placeholder': 'Wählen Sie Ihr Level',
    'salary_planner.calculate_cta': 'Gehaltsspanne berechnen',
    'salary_planner.calculating': 'Wird berechnet...',
    'salary_planner.toast.fill_fields': 'Bitte füllen Sie alle Felder aus',
    'salary_planner.toast.estimate_info': 'Geschätzte Werte basierend auf Durchschnittsdaten',
    'salary_planner.toast.error': 'Fehler beim Berechnen der Gehaltsschätzung',
    'salary_planner.estimation_title': 'Gehaltsschätzung',
    'salary_planner.minimum': 'Minimum',
    'salary_planner.per_year': 'pro Jahr',
    'salary_planner.per_month': 'pro Monat',
    'salary_planner.median': 'Median',
    'salary_planner.maximum': 'Maximum',
    'salary_planner.data_points': 'Basierend auf {dataPoints} Datenpunkten',
    'salary_planner.estimated_values': 'Geschätzte Werte • Aktuelle Marktdaten werden gesammelt',
    'salary_planner.notes_title': 'Hinweise:',
    'salary_planner.note1': '• Gehälter können je nach Arbeitgeber und Region variieren',
    'salary_planner.note2': '• Zusatzleistungen und Boni sind nicht enthalten',
    'salary_planner.note3': '• Brutto-Jahresgehalt vor Steuern',
    'salary_planner.note4': '• Werte basieren auf Vollzeitstellen',

    // Privacy Settings
    'privacy_settings.title': 'Datenschutz & DSGVO',
    'privacy_settings.subtitle': 'Verwalten Sie Ihre Daten und Privatsphäre-Einstellungen',
    'privacy_settings.recommendations_title': 'Jobempfehlungen',
    'privacy_settings.recommendations_description': 'Steuern Sie, wie wir Ihnen personalisierte Jobs vorschlagen.',
    'privacy_settings.enable_recommendations': 'Empfehlungen aktivieren',
    'privacy_settings.show_personalized_jobs': 'Personalisierte Jobs basierend auf Ihrem Profil anzeigen',
    'privacy_settings.email_notifications': 'E-Mail Benachrichtigungen',
    'privacy_settings.receive_new_jobs_email': 'Neue passende Jobs per E-Mail erhalten',
    'privacy_settings.email_frequency': 'E-Mail-Häufigkeit',
    'privacy_settings.daily': 'Täglich',
    'privacy_settings.weekly': 'Wöchentlich',
    'privacy_settings.biweekly': 'Alle 2 Wochen',
    'privacy_settings.monthly': 'Monatlich',
    'privacy_settings.data_retention_title': 'Datenaufbewahrung',
    'privacy_settings.data_retention_description': 'Bestimmen Sie, wie lange Ihre Daten gespeichert werden sollen.',
    'privacy_settings.retention_days': 'Aufbewahrungsdauer (Tage)',
    'privacy_settings.retention_days_hint': 'Minimum 30 Tage, Maximum 10 Jahre (3650 Tage)',
    'privacy_settings.enable_auto_delete': 'Automatische Löschung aktivieren',
    'privacy_settings.auto_delete_description': 'Daten werden nach Ablauf der Frist automatisch gelöscht',
    'privacy_settings.save_settings': 'Einstellungen speichern',
    'privacy_settings.toast.save_success': 'Einstellungen gespeichert',
    'privacy_settings.toast.save_error': 'Fehler beim Speichern',
    'privacy_settings.data_export_title': 'Datenexport',
    'privacy_settings.data_export_description': 'Laden Sie eine Kopie all Ihrer gespeicherten Daten herunter (DSGVO Art. 15).',
    'privacy_settings.export_my_data': 'Meine Daten exportieren',
    'privacy_settings.toast.export_success': 'Daten exportiert',
    'privacy_settings.data_deletion_title': 'DSGVO-Datenlöschung',
    'privacy_settings.data_deletion_description': 'Sie haben das Recht, die Löschung Ihrer personenbezogenen Daten gemäß DSGVO Art. 17 zu beantragen. Wählen Sie aus, welche Daten gelöscht werden sollen.',
    'privacy_settings.delete_applications_only': 'Nur Bewerbungsdaten löschen',
    'privacy_settings.delete_messages_only': 'Nur Nachrichten löschen',
    'privacy_settings.delete_full_account': 'Komplettes Konto löschen (unwiderruflich)',
    'privacy_settings.notes_optional': 'Anmerkungen (optional)',
    'privacy_settings.notes_placeholder': 'Zusätzliche Informationen oder Gründe für die Löschung...',
    'privacy_settings.warning_full_account_deletion': 'Achtung: Die vollständige Kontolöschung kann nicht rückgängig gemacht werden. Alle Ihre Daten werden dauerhaft entfernt.',
    'privacy_settings.warning_data_deletion': 'Diese Aktion löscht die ausgewählten Daten dauerhaft aus unserem System.',
    'privacy_settings.submit_deletion_request': 'Löschantrag einreichen',
    'privacy_settings.deletion_confirm_title': 'Datenlöschung bestätigen',
    'privacy_settings.deletion_confirm_full_account': 'Sie sind dabei, Ihr komplettes Konto zu löschen. Diese Aktion kann nicht rückgängig gemacht werden. Sind Sie sicher?',
    'privacy_settings.deletion_confirm_data': 'Sie sind dabei, einen Löschantrag für Ihre {requestType} einzureichen. Sind Sie sicher?',
    'privacy_settings.toast.deletion_request_submitted': 'Löschantrag eingereicht',
    'privacy_settings.toast.deletion_request_submitted_description': 'Ihr Antrag wird bearbeitet. Sie erhalten eine Bestätigung per E-Mail.',
    'privacy_settings.toast.deletion_request_error': 'Der Antrag konnte nicht eingereicht werden.',
    'privacy_settings.deletion_requests_history_title': 'Löschanträge',
    'privacy_settings.request_type_applications': 'Bewerbungsdaten',
    'privacy_settings.request_type_messages': 'Nachrichten',
    'privacy_settings.request_type_full_account': 'Komplettes Konto',
    'privacy_settings.status_pending': 'Ausstehend',
    'privacy_settings.status_processing': 'In Bearbeitung',
    'privacy_settings.status_completed': 'Abgeschlossen',
    'privacy_settings.status_cancelled': 'Abgebrochen',
    'privacy_settings.submitted_on': 'Eingereicht am',
    'privacy_settings.completed_on': 'Abgeschlossen am',
    'privacy_settings.title_short': 'Datenschutz',

    // Cookie Consent
    'cookie_consent.title': 'Ihre Cookie-Einstellungen',
    'cookie_consent.description': 'Wir verwenden Cookies, um die Funktionalität der Website zu gewährleisten und Ihre Erfahrung zu verbessern. Sie können Ihre Einstellungen jederzeit anpassen.',
    'cookie_consent.learn_more': 'Mehr erfahren',
    'cookie_consent.accept_all': 'Alle akzeptieren',
    'cookie_consent.reject_all': 'Alle ablehnen',
    'cookie_consent.customize': 'Anpassen',
    'cookie_consent.settings_title': 'Cookie-Einstellungen verwalten',
    'cookie_consent.settings_description': 'Hier können Sie Ihre Präferenzen für Cookies und Tracking-Technologien anpassen.',
    'cookie_consent.detailed_policy': 'Detaillierte Cookie-Richtlinie',
    'cookie_consent.essential': 'Essenzielle Cookies',
    'cookie_consent.always_active': 'Immer aktiv',
    'cookie_consent.essential_description': 'Diese Cookies sind für die grundlegende Funktion der Website unerlässlich und können nicht deaktiviert werden.',
    'cookie_consent.analytics': 'Analyse-Cookies',
    'cookie_consent.analytics_description': 'Diese Cookies helfen uns zu verstehen, wie Besucher mit der Website interagieren, indem sie Informationen anonym sammeln und berichten.',
    'cookie_consent.marketing': 'Marketing-Cookies',
    'cookie_consent.marketing_description': 'Diese Cookies werden verwendet, um Besuchern auf Websites zu folgen. Ziel ist es, Anzeigen zu schalten, die für den einzelnen Nutzer relevant und ansprechend sind.',
    'cookie_consent.save_preferences': 'Einstellungen speichern',
  },
  en: {
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.saved': 'Saved',
    'nav.applications': 'Applications',
    'nav.admin': 'Admin',
    'nav.employer': 'Employer',
    'nav.logout': 'Sign Out',
    'nav.login': 'Sign In',
    
    // Menu
    'menu.browse': 'Browse',
    'menu.home': 'Home',
    'menu.my_pflegeflix': 'My Pflegeflix',
    'menu.dashboard': 'Dashboard',
    'menu.for_you': 'For You',
    'menu.career': 'My Career',
    'menu.saved_jobs': 'Saved Jobs',
    'menu.applications': 'Applications',
    'menu.account_settings': 'Account Settings',
    'menu.categories': 'Categories',
    'menu.post_job': 'Post Job',
    'menu.my_jobs': 'My Jobs',
    'menu.applicants': 'Applicants',
    'menu.settings': 'Settings',
    'menu.moderation': 'Moderation',
    'menu.data_view': 'Data View',
    'menu.legal_settings': 'Legal Settings',
    'menu.language': 'Language',
    'menu.legal': 'Legal',
    'menu.switch_role': 'Switch Role',
    'menu.sign_out': 'Sign Out',
    'menu.sign_in': 'Sign In',
    'menu.sign_up': 'Sign Up',
    'menu.close': 'Close menu',
    
    // Footer
    'footer.impressum': 'Imprint',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookie Policy',
    
    // Auth
    'auth.switching_role': 'Switching role...',
    'auth.switch_role': 'Switch role',
    'auth.confirm_password': 'Confirm password',
    'auth.passwords_match': 'Passwords match',
    'auth.passwords_no_match': 'Passwords do not match',
    'auth.success.account_created': 'Account successfully created! Please confirm your email address.',
    'auth.error.title': 'Login Error',
    'auth.error.invalid_credentials': 'Invalid login credentials. Please check your email and password.',
    'auth.error.email_not_confirmed': 'Your email address is not yet confirmed. Please check your inbox.',
    'auth.error.too_many_requests': 'Too many login attempts. Please try again later.',
    'auth.error.network': 'Network error. Please check your internet connection.',
    'auth.error.generic': 'An unexpected error occurred. Please try again.',
    'auth.error.try_again': 'Try Again',
    'auth.error.reset_password': 'Reset Password',
    'auth.error.create_account': 'Create Account',
    'auth.password.hide': 'Hide password',
    'auth.password.show': 'Show password',
    'auth.password.visible': 'Password is visible',
    'auth.password.hidden': 'Password is hidden',
    'auth.login_required.title': 'Login Required',
    'auth.login_required.message': 'Please log in or register to use this feature.',
    'auth.login_required.save_hint': 'Login to save',
    
    // Employer Portal
    'employer.portal_title': 'Employer Portal',
    'employer.portal_subtitle': 'Manage your jobs and applicants',
    'employer.my_jobs': 'My Jobs',
    'employer.post_job': 'Post Job',
    'employer.applicants': 'Applicants',
    'employer.settings': 'Settings',
    'employer.settings_page_title': 'Settings',
    'employer.settings_page_description': 'Manage your employer settings and templates',
    'employer.settings_page_subtitle': 'Customize your settings',
    'employer.message_templates': 'Message Templates',
    
    // Categories
    'category.clinics': 'Clinics',
    'category.hospital': 'Hospital',
    'category.hospitals': 'Hospitals',
    'category.nursing_homes': 'Nursing Homes',
    'category.intensive_care': 'Intensive Care',
    'category.section': 'Categories',
    'category.back': 'Back',
    'category.edit_order': 'Edit order',
    'category.done': 'Done',
    
    // Dashboard
    'dashboard.my_jobs': 'My Jobs',
    'dashboard.jobs_total': 'jobs total',
    'dashboard.export': 'Export',
    'dashboard.search_placeholder': 'Search jobs...',
    'dashboard.copy': 'Copy',
    'dashboard.empty.title': 'No jobs yet',
    'dashboard.empty.description': 'Publish your first job and reach qualified healthcare professionals.',
    'dashboard.empty.cta': 'Publish First Job',
    'dashboard.filter.all_status': 'All Status',
    'dashboard.filter.all_categories': 'All Categories',
    'dashboard.filter.draft': 'Draft',
    'dashboard.filter.online': 'Active',
    'dashboard.filter.paused': 'Paused',
    'dashboard.filter.closed': 'Closed',
    'dashboard.filter.expired': 'Expired',
    'dashboard.sort.newest': 'Newest',
    'dashboard.sort.applications': 'Most Applications',
    'dashboard.sort.views': 'Most Views',
    'dashboard.status.draft': 'Draft',
    'dashboard.status.online': 'Active',
    'dashboard.status.paused': 'Paused',
    'dashboard.status.closed': 'Closed',
    'dashboard.status.expired': 'Expired',
    'dashboard.table.title': 'Title',
    'dashboard.table.location': 'Location',
    'dashboard.table.status': 'Status',
    'dashboard.table.views': 'Views',
    'dashboard.table.applications': 'Applications',
    'dashboard.table.metrics': 'Metrics',
    'dashboard.table.saved': 'Saved',
    'dashboard.table.updated': 'Updated',
    'dashboard.table.actions': 'Actions',
    'dashboard.job.closed': 'Job closed successfully',
    'dashboard.bulk.selected': 'selected',
    'dashboard.bulk.pause': 'Pause',
    'dashboard.bulk.resume': 'Resume',
    'dashboard.bulk.close': 'Close',
    'dashboard.bulk.delete': 'Delete',
    'dashboard.bulk.pause_success': 'Jobs paused',
    'dashboard.bulk.resume_success': 'Jobs activated',
    'dashboard.bulk.close_success': 'Jobs closed',
    'dashboard.bulk.delete_success': 'Jobs deleted',
    'dashboard.bulk.delete_confirm': 'Are you sure you want to delete the selected jobs?',
    'dashboard.action.preview': 'Preview',
    'dashboard.action.edit': 'Edit',
    'dashboard.action.pause': 'Pause',
    'dashboard.action.resume': 'Resume',
    'dashboard.action.delete': 'Delete',
    'dashboard.welcome': 'Welcome',
    'dashboard.user': 'User',
    'dashboard.manage_profile_applications': 'Manage your profile and applications',
    'dashboard.saved_jobs': 'Saved Jobs',
    'dashboard.applications': 'Applications',
    'dashboard.saved_searches': 'Saved Searches',
    'dashboard.coming_soon': 'Coming soon',
    'dashboard.overview': 'Overview',
    'dashboard.profile': 'Profile',
    'dashboard.recent_applications': 'Recent Applications',
    'dashboard.last_5_applications': 'Your last 5 applications',
    'dashboard.no_applications_yet': 'No applications yet',
    'dashboard.profile_summary': 'Profile Summary',
    'dashboard.profile_data': 'Your profile data',
    'dashboard.name': 'Name',
    'dashboard.not_specified': 'Not specified',
    'dashboard.email': 'Email',
    'dashboard.location': 'Location',
    'dashboard.skills': 'Skills',
    'dashboard.no_skills_specified': 'None specified',
    'dashboard.edit_profile': 'Edit Profile',
    'dashboard.edit_profile_title': 'Edit Profile',
    'dashboard.update_profile_info': 'Update your personal information and skills',
    'dashboard.email_cannot_be_changed': 'Email cannot be changed',
    'dashboard.city': 'City',
    'dashboard.state': 'State',
    'dashboard.add_skill_placeholder': 'e.g., Intensive Care, Wound Management',
    'dashboard.add': 'Add',
    'dashboard.save_changes': 'Save Changes',
    'dashboard.saving': 'Saving...',
    'dashboard.privacy_settings': 'Privacy Settings',
    'dashboard.jobs_for_later': 'Jobs you saved for later',
    'dashboard.no_saved_jobs': 'No saved jobs',
    'dashboard.no_saved_jobs_description': 'You haven\'t saved any jobs yet. Browse job listings and save interesting jobs.',
    'dashboard.browse_jobs': 'Browse Jobs',
    'dashboard.all_applications_overview': 'Overview of all your applications',
    'dashboard.no_applications_description': 'You haven\'t applied for any jobs yet. Find suitable positions and apply today!',
    'dashboard.applied_on': 'Applied',
    'dashboard.cover_letter_short': 'Cover Letter',
    'dashboard.stage.submitted': 'Submitted',
    'dashboard.stage.viewed': 'Viewed',
    'dashboard.stage.interview': 'Interview',
    'dashboard.stage.offer': 'Offer',
    'dashboard.stage.rejected': 'Rejected',
    'dashboard.application.stage_updated': 'Application stage updated',
    'dashboard.application.notes_saved': 'Notes saved',
    'dashboard.application.move_to': 'Move to',
    'dashboard.application.cover_letter': 'Cover Letter',
    'dashboard.application.notes': 'Notes',
    'dashboard.application.notes_placeholder': 'Add private notes about this applicant...',
    
    // Applicants
    'applicants.title': 'Applicants',
    'applicants.subtitle': 'Manage all incoming applications',
    'applicants.empty_title': 'No applications yet',
    'applicants.empty_description': 'No applications yet — publish your first job.',
    'applicants.empty_action': 'Post Job',
    'applicants.exported': 'Applications exported',
    'applicants.export': 'Export',
    'applicants.all': 'All Applicants',
    'applicants.by_job': 'By Job',
    'applicants.search_placeholder': 'Search applicants…',
    'applicants.all_stages': 'All Stages',
    'applicants.submitted': 'Submitted',
    'applicants.viewed': 'Viewed',
    'applicants.interview': 'Interview',
    'applicants.offer': 'Offer',
    'applicants.rejected': 'Rejected',
    'applicants.select_job_hint': 'Select a job to view applicants.',
    'applicants.filter_stage': 'Filter by stage',
    'applicants.filter_job': 'Filter by job',
    'applicants.all_jobs': 'All Jobs',
    'applicants.selected': 'selected',
    'applicants.change_stage': 'Change stage',
    'applicants.delete_selected': 'Delete selected',
    'applicants.applicant': 'Applicant',
    'applicants.job': 'Job',
    'applicants.stage': 'Stage',
    'applicants.rating': 'Rating',
    'applicants.applied': 'Applied',
    'applicants.actions': 'Actions',
    'applicants.total': 'Total',
    'applicants.bulk_deleted': 'Applications deleted',
    'applicants.bulk_updated': 'Applications updated',
    'applicants.view': 'View',
    'applicants.no_results': 'No results found',
    'applicants.no_results_description': 'Try adjusting your filters or resetting the search.',
    'applicants.clear_filters': 'Clear filters',
    'applicants.applied_for': 'Applied for',
    'applicants.pipeline_stage': 'Pipeline Stage',
    'applicants.cover_letter': 'Cover Letter',
    'applicants.internal_notes': 'Internal Notes',
    'applicants.notes_placeholder': 'Add private notes about this applicant...',
    'applicants.save_notes': 'Save Notes',
    'applicants.tags': 'Tags',
    'applicants.add_tag': 'Add tag...',
    'applicants.add': 'Add',
    'applicants.messages': 'Messages',
    'applicants.message_placeholder': 'Send message to applicant...',
    'applicants.message_sent': 'Message sent',
    'applicants.activity': 'Activity',
    'applicants.system': 'System',
    'applicants.changed_stage_from': 'changed stage from',
    'applicants.to': 'to',
    'applicants.you': 'You',
    'applicants.stage_updated': 'Stage updated',
    'applicants.rating_updated': 'Rating updated',
    'applicants.recommend': 'Recommend',
    'applicants.recommend_updated': 'Recommendation updated',
    'applicants.delete_confirm': 'Are you sure you want to delete this applicant? This action cannot be undone.',
    'applicants.deleted': 'Applicant deleted',
    
    // Saved Searches
    'saved_searches.title': 'Saved Searches',
    'saved_searches.subtitle': 'Manage your saved filters and email alerts.',
    'saved_searches.empty_title': 'No saved searches yet',
    'saved_searches.empty_description': 'Save a search to get email alerts when new jobs match your filters.',
    'saved_searches.empty_action': 'Create your first saved search',
    'saved_searches.filters_applied': 'filters',
    'saved_searches.email_alerts': 'Email Alerts',
    'saved_searches.alert_none': 'None',
    'saved_searches.alert_daily': 'Daily',
    'saved_searches.alert_weekly': 'Weekly',
    'saved_searches.view_results': 'View Results',
    'saved_searches.delete': 'Delete Search',
    'saved_searches.delete_confirm': 'Are you sure you want to delete this saved search? This action cannot be undone.',
    'saved_searches.deleted': 'Search deleted',
    'saved_searches.updated': 'Search updated',
    'saved_searches.rename': 'Rename Search',
    'saved_searches.search_name': 'Search name',
    'saved_searches.search_name_placeholder': 'e.g., "Nursing jobs in Berlin"',
    'saved_searches.unsubscribe_success': 'Email notifications have been disabled',
    'saved_searches.unsubscribe_hint': 'You can unsubscribe anytime via the link in the email',
    
    // Favorites (Saved Jobs)
    'favorites.title': 'Saved Jobs',
    'favorites.removed': 'Job removed from favorites',
    'favorites.saved': 'Job saved',
    'favorites.description': 'Manage the jobs you saved for later',

    // Footer
    'footer.company_info': 'Company Information',
    'footer.legal': 'Legal',
    'footer.support': 'Privacy & Support',
    'footer.employers': 'For Employers',
    'footer.privacy_center': 'Privacy Center',
    'footer.candidate_privacy': 'Candidate Privacy',
    'footer.cookie_settings': 'Cookie Settings',
    'footer.dpa': 'Data Processing Agreement',
    'footer.post_job': 'Post a Job',
    'footer.rights': 'All rights reserved.',
    'footer.company_address': 'Pflegeflix GmbH, Sample Street 123, 10115 Berlin, Germany',
    'footer.accessibility': 'Accessibility',
    
    // Job posting
    'job.published_success': 'Job published successfully',
    'job.publish_success.title': 'Job Posted Successfully!',
    'job.publish_success.description': 'Your job posting is now live and visible to candidates.',
    'job.publish_success.view_my_jobs': 'View My Jobs',
    'job.publish_success.view_posting': 'View Job Posting',
    'job.publish_success.post_another': 'Post Another Job',
    'job.no_slots.title': 'No Available Job Posting Slots',
    'job.no_slots.description': 'You have reached your job posting limit for your current plan.',
    'job.no_slots.upgrade': 'Upgrade Plan',
    'job.no_slots.manage_jobs': 'Manage Existing Jobs',
    'job.draft_saved': 'Draft saved',
    'job.delete_confirm': 'Are you sure you want to delete this job?',
    'job.step1.title': 'Step 1 – Basics',
    'job.field.title': 'Job Title',
    'job.field.title_placeholder': 'e.g., Registered Nurse',
    'job.field.category': 'Category',
    'job.field.category_placeholder': 'Select a category',
    'job.field.city': 'City',
    'job.field.city_placeholder': 'Select a city',
    'job.field.state': 'State',
    'job.field.state_placeholder': 'Select a state',
    'job.post.back': 'Back',
    'job.post.save_draft': 'Save Draft',
    'job.post.next': 'Next',
    'job.toast.paused': 'Job paused',
    'job.toast.activated': 'Job activated',
    'job.toast.deleted': 'Job deleted',
    'job.new': 'New',
    'job.apply': 'Apply now',
    'job.days_ago': 'Posted {days} days ago',
    'job.field.description': 'Description',
    'job.field.description_placeholder': 'Describe the duties and responsibilities...',
    'job.field.requirements': 'Requirements',
    'job.field.requirement_placeholder': 'e.g., Completed training as a healthcare professional',
    'job.field.add_requirement': 'Add requirement',
    'job.field.specialties': 'Specialties',
    'job.field.shift_type': 'Shift Type',
    'job.field.shift_placeholder': 'e.g., Day shift, Night shift, Rotating shift',
    'job.step2.title': 'Step 2 – Details',
    'job.step3.title': 'Step 3 – Compensation',
    'job.field.salary_min': 'Minimum Salary',
    'job.field.salary_max': 'Maximum Salary',
    'job.field.salary_unit': 'Salary Unit',
    'job.field.salary_unit_placeholder': 'Select unit',
    'job.field.contract_type': 'Contract Type',
    'job.field.contract_placeholder': 'Select contract type',
    'job.field.featured': 'Featured',
    'job.field.featured_desc': 'Place job posting prominently on the homepage',
    'job.step4.title': 'Step 4 – Application',
    'job.field.application_method': 'Application Method',
    'job.field.application_email': 'Apply by Email',
    'job.field.application_external': 'External Link',
    'job.field.email': 'Email',
    'job.field.url': 'URL',
    'job.field.auto_reply': 'Auto-Reply',
    'job.field.auto_reply_placeholder': 'Optional: Message applicants receive after submitting',
    'job.field.contact_person': 'Contact Person',
    'job.field.contact_placeholder': 'Optional: Name of contact person for applications',
    'job.step5.title': 'Step 5 – Preview & Publish',
    'job.post.step': 'Step',
    'job.post.of': 'of',
    'job.post.publish': 'Publish Job',
    'job.apply_for_position': 'Apply for this position',
    'job.at_facility': 'at',
    'job.default_facility': 'a facility',
    'job.competitive_salary': 'Competitive Salary',
    'job.apply_now_description': 'Apply for this position now.',
    'job.remove_from_saved': 'Remove from saved',
    'job.save_job': 'Save job',
    'job.view_details_for': 'View details for {title} in {city}, {state}',
    'job.posted_days_ago': 'Posted {days} days ago',
    'job.tags_label': 'Tags',
    'job.salary_range_label': 'Salary range: {salary_min} to {salary_max} {salary_unit}',
    'job.by_agreement': 'By agreement',
    'job.contract_shift_label': 'Contract type: {contract_type}, Shift type: {shift_type}',
    'job.salary_label': 'Salary',
    'job.contract_label': 'Contract',
    'job.shift_label': 'Shift',
    'job.description_heading': 'Job Description',
    'job.requirements_heading': 'Requirements',
    'job.bonus_heading': 'Bonus',
    
    // Application
    'application.cover_letter': 'Cover letter (optional)',
    'application.success': 'Application submitted successfully!',
    'application.inbox_title': 'Applications',
    'application.select_app_message': 'Select an application to view messages',
    'application.message_input_placeholder': 'Enter message...',
    'application.message_sent_toast': 'Message sent',
    'application.send_message': 'Send message',
    'application.error_sending_message': 'Error sending message',
    'application.submitting': 'Submitting...',
    'applications.description': 'Manage your applications and communicate with employers.',
    'applications.subtitle': 'Your overview of all applications and messages',
    'applications.title_short': 'Privacy',
    
    // Carousels
    'carousel.recommended': 'Recommended',
    'carousel.clinics': 'Clinics & Hospitals',
    'carousel.nursing_homes': 'Nursing Homes',
    'carousel.one_on_one': '1:1 Intensive Care',
    'carousel.night_part': 'Night-Shift Picks',
    'carousel.for_you': 'For You',
    
    // Hero
    'hero.title': 'Your Dream Job in Healthcare',
    'hero.subtitle': 'Discover thousands of positions across Germany',
    
    // Message Templates
    'templates.title': 'Message Templates',
    'templates.new': 'New Template',
    'templates.edit': 'Edit',
    'templates.delete': 'Delete',
    'templates.delete_confirm': 'Are you sure you want to delete this template?',
    'templates.deleted': 'Template deleted',
    'templates.saved': 'Template saved',
    'templates.empty_title': 'No templates yet',
    'templates.empty_description': 'Create templates for frequently used messages.',
    'templates.empty_action': 'Create First Template',
    'templates.name': 'Name',
    'templates.subject': 'Subject',
    'templates.body': 'Message',
    'templates.type': 'Type',
    'templates.type_general': 'General',
    'templates.type_interview': 'Interview Invitation',
    'templates.type_offer': 'Job Offer',
    'templates.type_rejection': 'Rejection',
    'templates.use_template': 'Use template...',
    'templates.fill_all_fields': 'Please fill in all required fields',
    'templates.error_saving': 'Error saving',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.view': 'View',
    'common.no_results': 'No results',
    'common.view_results': 'View results',
    'common.rename': 'Rename',
    'common.rename_search': 'Rename search',
    'common.rename_description': 'Enter a new name for this search.',
    'common.delete_search': 'Delete search?',
    'common.delete_search_description': 'This action cannot be undone. The search and all associated email notifications will be deleted.',
    'common.name': 'Name',
    'common.created': 'Created',
    'common.never': 'Never',
    'common.daily': 'Daily',
    'common.weekly': 'Weekly',
    'loading': 'Loading...',
    'search.filters': 'Filters',
    'privacy_center.delete_cancel': 'Cancel',
    'cancel': 'Cancel',
    'common.download_pdf': 'Download PDF',
    'common.remove_item': 'Remove {item}',
    
    // Errors
    'error.unauthorized': 'Unauthorized',
    'error.load_failed': 'Loading failed',
    'error.update_failed': 'Update failed',
    'error.delete_failed': 'Delete failed',
    'error.duplicate_failed': 'Duplication failed',
    'error.generic': 'An error occurred',
    'error.page_not_found': 'Page not found',
    'error.page_not_found_description': 'Sorry, this page doesn\'t exist.',
    'navigation.go_back': 'Go Back',
    'navigation.to_search': 'To Job Search',
    'error.job_not_found': 'Job not found',
    'error.job_not_found_description': 'The job posting you are looking for does not exist or has been removed.',
    'error.required_fields': 'Please fill in all required fields.',
    'error.posting_limit_reached': 'Job Posting Limit Reached',
    'error.upgrade_subscription': 'Please upgrade your subscription to post more jobs.',
    'error.publish_failed': 'Publishing failed',
    'error.page_not_found_seo_title': 'Page Not Found - 404',
    'dashboard.load_data_error': 'Error loading dashboard data.',
    'dashboard.profile_saved': 'Profile saved',
    'dashboard.profile_saved_description': 'Your profile information has been successfully updated.',
    'error.save_failed': 'Save failed',
    'dashboard.profile_save_error': 'Error saving your profile information.',
    
    // Filters (used in LocationFilter & FullScreenFilterSheet)
    'filter.location': 'Location',
    'filter.search_cities': 'Search city…',
    'filter.remove_city': 'Remove {city} city',
    'filter.max_cities_reached': 'Maximum 3 cities selected',
    'filter.city_helper': 'Select up to 3 cities',
    'filter.close_menu': 'Close filter menu',
    
    // Saved Searches dialog (Search page)
    'saved_searches.save_current': 'Save current search',
    
    // Favorites page description
    'favorites.description': 'Manage the jobs you saved for later',
    
    // Job posting / filters
    'job.field.facility_type': 'Facility Type',

    // StepDetails specialty tag translations (subcategory.*)
    'subcategory.intensivstation': 'ICU',
    'subcategory.op_anästhesie': 'Surgery/Anesthesia',
    'subcategory.chirurgie': 'Surgery',
    'subcategory.internistik': 'Internal Medicine',
    'subcategory.notaufnahme': 'Emergency',
    'subcategory.dialyse': 'Dialysis',
    'subcategory.stationär': 'Inpatient',
    'subcategory.kurzzeitpflege': 'Short-term Care',
    'subcategory.demenz': 'Dementia',
    'subcategory.gerontopsychiatrie': 'Geriatric Psychiatry',
    'subcategory.leitung': 'Management',
    'subcategory.beatmung': 'Ventilation',
    'subcategory.homecare': 'Homecare',
    'subcategory.kinder': 'Children',
    'subcategory.nacht': 'Night',
    'subcategory.24h': '24 h',

    // Optional nav labels (for consistency if used)
    'nav.for_you': 'For You',
    'nav.career': 'My Career',

    // Legal Pages
    'legal.last_updated': 'Last updated',
    'legal.impressum.title': 'Imprint',
    'legal.impressum.provider': 'Service Provider',
    'legal.impressum.contact': 'Contact',
    'legal.impressum.representative': 'Represented by',
    'legal.impressum.register': 'Register Entry',
    'legal.impressum.vat': 'VAT ID',
    'legal.impressum.editorial': 'Responsible for Content',
    'legal.impressum.dispute': 'Dispute Resolution',
    'legal.impressum.dispute_text': 'The European Commission provides a platform for online dispute resolution (OS):',
    'legal.candidate.title': 'Candidate Privacy Notice',
    'legal.candidate.introduction': 'Introduction',
    'legal.candidate.introduction_text': 'This privacy notice explains how we process your personal data in connection with your application via our platform.',
    'legal.candidate.joint_roles': 'Joint Controllership',
    'legal.candidate.joint_roles_text': 'Pflegeflix and the respective employer are jointly responsible for processing your data.',
    'legal.candidate.data_types': 'Types of Data Processed',
    'legal.candidate.data_types_text': 'We process the data you provide to us as part of your application (e.g., name, contact details, CV, cover letter).',
    'legal.candidate.purposes': 'Purposes of Data Processing',
    'legal.candidate.purposes_text': 'Your data will be used exclusively for processing the application and for contacting you by the employer.',
    'legal.candidate.legal_basis': 'Legal Basis for Processing',
    'legal.candidate.legal_basis_text': 'Processing is based on Art. 6 para. 1 lit. b GDPR (initiation of contract) and Art. 6 para. 1 lit. a GDPR (your consent).',
    'legal.candidate.retention': 'Data Retention',
    'legal.candidate.retention_text': 'Your data will be stored for the duration of the application process and a maximum of 6 months thereafter, unless longer consent is given.',
    'legal.candidate.recipients': 'Recipients of Data',
    'legal.candidate.recipients_text': 'Your data will be transmitted to the employer to whom you apply.',
    'legal.candidate.rights': 'Your Rights as a Data Subject',
    'legal.candidate.rights_text': 'You have the right to information, rectification, erasure, restriction of processing, objection, and data portability.',
    'legal.cookies.title': 'Cookie Policy',
    'legal.cookies.introduction': 'Introduction',
    'legal.cookies.introduction_text': 'This Cookie Policy explains how Pflegeflix uses cookies and similar technologies on our website.',
    'legal.cookies.what_are': 'What are Cookies?',
    'legal.cookies.what_are_text': 'Cookies are small text files stored on your device by websites to retain information.',
    'legal.cookies.essential': 'Essential Cookies',
    'legal.cookies.essential_text': 'These cookies are essential for the basic functionality of the website and cannot be disabled.',
    'legal.cookies.analytics': 'Analytics Cookies',
    'legal.cookies.analytics_text': 'These cookies help us understand how visitors interact with the website by collecting and reporting information anonymously.',
    'legal.cookies.marketing': 'Marketing Cookies',
    'legal.cookies.marketing_text': 'These cookies are used to track visitors across websites. The intention is to display ads that are relevant and engaging for the individual user.',
    'legal.cookies.manage': 'Manage Your Cookie Settings',
    'legal.cookies.manage_text': 'You can adjust your cookie settings at any time:',
    'legal.cookies.withdrawal': 'Withdrawal of Consent',
    'legal.cookies.withdrawal_text': 'You can withdraw your consent to the use of cookies at any time by changing your settings.',
    'legal.cookies.third_party': 'Third-Party Cookies',
    'legal.cookies.third_party_text': 'We also use third-party cookies set by our partners.',
    'legal.cookies.rights': 'Your Rights',
    'legal.cookies.rights_text': 'You have the right to request information about the cookies we use and to restrict their use.',
    'legal.cookies.table.name': 'Name',
    'legal.cookies.table.provider': 'Provider',
    'legal.cookies.table.purpose': 'Purpose',
    'legal.cookies.table.duration': 'Duration',
    'legal.cookies.table.basis': 'Legal Basis',
    'legal.cookies.ga_purpose': 'Registers a unique ID that is used to generate statistical data on how the visitor uses the website.',
    'legal.cookies.gid_purpose': 'Registers a unique ID that is used to generate statistical data on how the visitor uses the website.',
    'legal.cookies.fbp_purpose': 'Used by Facebook to deliver a series of advertisement products such as real-time bidding from third party advertisers.',
    'legal.cookies.24_months': '24 months',
    'legal.cookies.24_hours': '24 hours',
    'legal.cookies.90_days': '90 days',
    'legal.dpa.title': 'Data Processing Agreement (DPA)',
    'legal.dpa.sign': 'Sign DPA',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.controller': 'Name and contact details of the controller',
    'legal.privacy.controller_details': 'Pflegeflix GmbH\nSample Street 123\n10115 Berlin\nGermany\nEmail: privacy@pflegeflix.de',
    'legal.privacy.dpo': 'Contact details of the data protection officer',
    'legal.privacy.dpo_details': 'A data protection officer is not legally required.',
    'legal.privacy.purposes': 'Purposes and legal bases of processing',
    'legal.privacy.purpose_account': 'Account management and job placement',
    'legal.privacy.purpose_account_text': 'We process your data to provide our platform services, manage your user account, and facilitate job placement. The legal basis is Art. 6 para. 1 lit. b GDPR (contract fulfillment).',
    'legal.privacy.purpose_jobs': 'Publication of job advertisements',
    'legal.privacy.purpose_jobs_text': 'Employer data is processed for the publication of job advertisements. The legal basis is Art. 6 para. 1 lit. b GDPR.',
    'legal.privacy.purpose_security': 'Security and fraud prevention',
    'legal.privacy.purpose_security_text': 'To ensure the security of our systems and prevent fraud, we process access data. The legal basis is Art. 6 para. 1 lit. f GDPR (legitimate interest).',
    'legal.privacy.purpose_email': 'Email communication',
    'legal.privacy.purpose_email_text': 'We use your email address for communication within the scope of job placement and for notifications. The legal basis is Art. 6 para. 1 lit. b GDPR.',
    'legal.privacy.recipients': 'Recipients or categories of recipients of personal data',
    'legal.privacy.recipients_details': 'Your data will be transmitted to the respective employer to whom you apply. We also use service providers for hosting and email delivery.',
    'legal.privacy.data_categories': 'Categories of personal data',
    'legal.privacy.data_categories_details': 'We process master data (name, address), contact data (email, phone), application data (CV, cover letter), and usage data (IP address, access times).',
    'legal.privacy.transfers': 'Transfer of personal data to a third country',
    'legal.privacy.transfers_details': 'A transfer to third countries outside the EU/EEA only takes place if necessary for contract fulfillment or if you have given your consent.',
    'legal.privacy.retention': 'Duration of storage of personal data',
    'legal.privacy.retention_details': 'Data will be deleted as soon as it is no longer required for the purposes for which it was collected, or you withdraw your consent.',
    'legal.privacy.rights': 'Your rights as a data subject',
    'legal.privacy.rights_details': 'You have the right to information, rectification, erasure, restriction of processing, objection, and data portability.',
    'legal.privacy.complaint': 'Right to lodge a complaint with a supervisory authority',
    'legal.privacy.complaint_details': 'You have the right to lodge a complaint with a data protection supervisory authority regarding the processing of your personal data.',
    'legal.privacy.requirement': 'Necessity of providing personal data',
    'legal.privacy.requirement_details': 'The provision of your data is necessary for the use of our services. Without this data, we cannot fulfill the contract.',
    'legal.privacy.automated': 'Existence of automated decision-making',
    'legal.privacy.automated_details': 'No automated decision-making, including profiling, takes place.',

    // Search Page
    'search.title': 'Job Search',
    'search.description_base': 'Find your next job in healthcare.',
    'search.jobs_find': 'jobs',
    'search.placeholder': 'Job title, location, keyword...',
    'search.min_salary': 'Min: {value}€',
    'search.max_salary': 'Max: {value}€',
    'search.city_helper': 'Select up to 3 cities',
    'search.max_cities_reached': 'Maximum 3 cities selected',
    'search.search_cities': 'Search city…',
    'search.remove_city': 'Remove {city} city',
    'search.apply_filters': 'Apply Filters',
    'search.clear': 'Clear',
    'search.location': 'Location',
    'search.top_specialties': 'Top (Recommended)',
    'search.other_specialties': 'Other',
    'search.no_specialties_found': 'No specialties found',
    'search.show_more': 'Show more ({count})',
    'search.show_less': 'Show less',
    'search.active_filters': 'active filters',
    'search.remove_filter': 'Remove {filter}',
    'search.min_salary_label': 'Minimum Salary',
    'search.max_salary_label': 'Maximum Salary',
    'search.posted_label': 'Posted',
    'search.posted_options.24h': 'Last 24 hours',
    'search.posted_options.7d': 'Last 7 days',
    'search.posted_options.30d': 'Last 30 days',
    'search.no_info': 'No info',
    'search.radius_around': 'Radius around {city}',
    'search.show_results': 'Show {count} results',
    'search.filter_options': 'Filter options',
    'search.close_menu': 'Close filter menu',
    'search.reset_all_filters': 'Reset all filters',
    'search.search_specialties': 'Search specialty…',
    'search.selected_count': 'Selected ({count})',
    'search.no_jobs_found': 'No jobs found',
    'search.no_jobs_found_description': 'Try adjusting your filters or resetting the search.',
    'search.no_jobs_available': 'No jobs available',
    'search.no_jobs_available_description': 'Currently no jobs are available. Please try again later or adjust your search.',
    'search.reset_filters': 'Reset Filters',
    'search.results_region_label': 'Search results',

    // Contract Types
    'contract.Vollzeit': 'Full-time',
    'contract.Teilzeit': 'Part-time',
    'contract.Minijob': 'Mini-job',
    'contract.Befristet': 'Temporary',

    // Shift Types
    'shift_type.tagschicht': 'Day shift',
    'shift_type.nachtschicht': 'Night shift',
    'shift_type.wechselschicht': 'Rotating shift',
    'shift_type.bereitschaftsdienst': 'On-call duty',
    
    // Career Tools
    'career.title': 'My Career',
    'career.subtitle': 'Professional tools for your application and career planning',
    'career.cv_builder_title': 'CV Builder',
    'career.cv_builder_description': 'Create a professional CV with templates for healthcare',
    'career.cv_builder_cta': 'Create CV',
    'career.cover_letter_ai_title': 'AI Cover Letter',
    'career.cover_letter_ai_description': 'Generate tailored cover letters with artificial intelligence',
    'career.cover_letter_ai_cta': 'Generate Cover Letter',
    'career.salary_planner_title': 'Salary Planner',
    'career.salary_planner_description': 'Compare salary ranges by role, experience, and region',
    'career.salary_planner_cta': 'Compare Salary',
    'career.tip_title': '💡 Tip',
    'career.tip_description': 'Use all three tools to optimally prepare your application. Your created CV can be used directly for applications!',

    // CV Builder
    'cv_builder.title': 'CV Builder',
    'cv_builder.save': 'Save',
    'cv_builder.saving': 'Saving...',
    'cv_builder.download_pdf': 'As PDF',
    'cv_builder.personal_info_title': 'Personal Information',
    'cv_builder.name': 'Name',
    'cv_builder.email': 'Email',
    'cv_builder.phone': 'Phone',
    'cv_builder.city': 'City',
    'cv_builder.work_experience_title': 'Work Experience',
    'cv_builder.add_experience': 'Add',
    'cv_builder.position': 'Position',
    'cv_builder.job_title_placeholder': 'Job Title',
    'cv_builder.company_placeholder': 'Company',
    'cv_builder.start_date_placeholder': 'Start Date',
    'cv_builder.end_date_placeholder': 'End Date',
    'cv_builder.description_placeholder': 'Description',
    'cv_builder.education_title': 'Education',
    'cv_builder.add_education': 'Add',
    'cv_builder.degree_placeholder': 'Degree',
    'cv_builder.institution_placeholder': 'Institution',
    'cv_builder.year_placeholder': 'Year',
    'cv_builder.skills_title': 'Skills',
    'cv_builder.skills_placeholder': 'Enter your skills (comma-separated)',
    'cv_builder.toast.save_success': 'CV saved!',
    'cv_builder.toast.save_error': 'Error saving CV',
    'cv_builder.toast.pdf_soon': 'PDF export will be available soon',

    // Cover Letter Generator
    'cover_letter.title': 'AI Cover Letter Generator',
    'cover_letter.subtitle': 'Create a professional, job-tailored cover letter',
    'cover_letter.job_details_title': 'Job Details',
    'cover_letter.job_title': 'Job Title *',
    'cover_letter.job_title_placeholder': 'e.g., Registered Nurse',
    'cover_letter.company_name': 'Company / Facility *',
    'cover_letter.company_name_placeholder': 'e.g., University Hospital Berlin',
    'cover_letter.facility_type': 'Facility Type (optional)',
    'cover_letter.facility_type_placeholder': 'e.g., Hospital, Nursing Home',
    'cover_letter.generate_cta': 'Generate Cover Letter with AI',
    'cover_letter.generating': 'Generating...',
    'cover_letter.toast.fill_fields': 'Please fill in all required fields',
    'cover_letter.toast.generate_success': 'Cover letter generated!',
    'cover_letter.toast.generate_error': 'Error generating cover letter',
    'cover_letter.your_cover_letter_title': 'Your Cover Letter',
    'cover_letter.copy': 'Copy',
    'cover_letter.download': 'Download',
    'cover_letter.toast.copy_success': 'Copied to clipboard!',
    'cover_letter.toast.download_success': 'Cover letter downloaded!',
    'cover_letter.edit_hint': 'You can edit the generated text before using it.',

    // Salary Planner
    'salary_planner.title': 'Salary Planner',
    'salary_planner.subtitle': 'Compare salary ranges based on role, experience, and region',
    'salary_planner.your_details_title': 'Your Details',
    'salary_planner.role': 'Job Title',
    'salary_planner.select_role_placeholder': 'Select a role',
    'salary_planner.state': 'State',
    'salary_planner.select_state_placeholder': 'Select a state',
    'salary_planner.facility_type': 'Facility Type',
    'salary_planner.select_type_placeholder': 'Select a type',
    'salary_planner.experience_level': 'Experience Level',
    'salary_planner.select_level_placeholder': 'Select your level',
    'salary_planner.calculate_cta': 'Calculate Salary Range',
    'salary_planner.calculating': 'Calculating...',
    'salary_planner.toast.fill_fields': 'Please fill in all fields',
    'salary_planner.toast.estimate_info': 'Estimated values based on average data',
    'salary_planner.toast.error': 'Error calculating salary estimate',
    'salary_planner.estimation_title': 'Salary Estimate',
    'salary_planner.minimum': 'Minimum',
    'salary_planner.per_year': 'per year',
    'salary_planner.per_month': 'per month',
    'salary_planner.median': 'Median',
    'salary_planner.maximum': 'Maximum',
    'salary_planner.data_points': 'Based on {dataPoints} data points',
    'salary_planner.estimated_values': 'Estimated values • Current market data is being collected',
    'salary_planner.notes_title': 'Notes:',
    'salary_planner.note1': '• Salaries may vary depending on employer and region',
    'salary_planner.note2': '• Additional benefits and bonuses are not included',
    'salary_planner.note3': '• Gross annual salary before taxes',
    'salary_planner.note4': '• Values are based on full-time positions',

    // Privacy Settings
    'privacy_settings.title': 'Privacy & GDPR Settings',
    'privacy_settings.subtitle': 'Manage your data and privacy settings',
    'privacy_settings.recommendations_title': 'Job Recommendations',
    'privacy_settings.recommendations_description': 'Control how we suggest personalized jobs to you.',
    'privacy_settings.enable_recommendations': 'Enable Recommendations',
    'privacy_settings.show_personalized_jobs': 'Show personalized jobs based on your profile',
    'privacy_settings.email_notifications': 'Email Notifications',
    'privacy_settings.receive_new_jobs_email': 'Receive new matching jobs by email',
    'privacy_settings.email_frequency': 'Email Frequency',
    'privacy_settings.daily': 'Daily',
    'privacy_settings.weekly': 'Weekly',
    'privacy_settings.biweekly': 'Bi-weekly',
    'privacy_settings.monthly': 'Monthly',
    'privacy_settings.data_retention_title': 'Data Retention',
    'privacy_settings.data_retention_description': 'Determine how long your data should be stored.',
    'privacy_settings.retention_days': 'Retention Period (Days)',
    'privacy_settings.retention_days_hint': 'Minimum 30 days, Maximum 10 years (3650 days)',
    'privacy_settings.enable_auto_delete': 'Enable Automatic Deletion',
    'privacy_settings.auto_delete_description': 'Data will be automatically deleted after the period expires',
    'privacy_settings.save_settings': 'Save Settings',
    'privacy_settings.toast.save_success': 'Settings saved',
    'privacy_settings.toast.save_error': 'Error saving',
    'privacy_settings.data_export_title': 'Data Export',
    'privacy_settings.data_export_description': 'Download a copy of all your stored data (GDPR Art. 15).',
    'privacy_settings.export_my_data': 'Export My Data',
    'privacy_settings.toast.export_success': 'Data exported',
    'privacy_settings.data_deletion_title': 'GDPR Data Deletion',
    'privacy_settings.data_deletion_description': 'You have the right to request the deletion of your personal data in accordance with GDPR Art. 17. Select which data should be deleted.',
    'privacy_settings.delete_applications_only': 'Delete application data only',
    'privacy_settings.delete_messages_only': 'Delete messages only',
    'privacy_settings.delete_full_account': 'Delete entire account (irreversible)',
    'privacy_settings.notes_optional': 'Notes (optional)',
    'privacy_settings.notes_placeholder': 'Additional information or reasons for deletion...',
    'privacy_settings.warning_full_account_deletion': 'Warning: Full account deletion cannot be undone. All your data will be permanently removed.',
    'privacy_settings.warning_data_deletion': 'This action will permanently delete the selected data from our system.',
    'privacy_settings.submit_deletion_request': 'Submit Deletion Request',
    'privacy_settings.deletion_confirm_title': 'Confirm Data Deletion',
    'privacy_settings.deletion_confirm_full_account': 'You are about to delete your entire account. This action cannot be undone. Are you sure?',
    'privacy_settings.deletion_confirm_data': 'You are about to submit a deletion request for your {requestType}. Are you sure?',
    'privacy_settings.toast.deletion_request_submitted': 'Deletion request submitted',
    'privacy_settings.toast.deletion_request_submitted_description': 'Your request will be processed. You will receive a confirmation by email.',
    'privacy_settings.toast.deletion_request_error': 'The request could not be submitted.',
    'privacy_settings.deletion_requests_history_title': 'Deletion Requests',
    'privacy_settings.request_type_applications': 'application data',
    'privacy_settings.request_type_messages': 'messages',
    'privacy_settings.request_type_full_account': 'entire account',
    'privacy_settings.status_pending': 'Pending',
    'privacy_settings.status_processing': 'Processing',
    'privacy_settings.status_completed': 'Completed',
    'privacy_settings.status_cancelled': 'Cancelled',
    'privacy_settings.submitted_on': 'Submitted on',
    'privacy_settings.completed_on': 'Completed on',
    'privacy_settings.title_short': 'Privacy',

    // Cookie Consent
    'cookie_consent.title': 'Your Cookie Settings',
    'cookie_consent.description': 'We use cookies to ensure website functionality and enhance your experience. You can adjust your settings at any time.',
    'cookie_consent.learn_more': 'Learn more',
    'cookie_consent.accept_all': 'Accept All',
    'cookie_consent.reject_all': 'Reject All',
    'cookie_consent.customize': 'Customize',
    'cookie_consent.settings_title': 'Manage Cookie Settings',
    'cookie_consent.settings_description': 'Here you can adjust your preferences for cookies and tracking technologies.',
    'cookie_consent.detailed_policy': 'Detailed Cookie Policy',
    'cookie_consent.essential': 'Essential Cookies',
    'cookie_consent.always_active': 'Always active',
    'cookie_consent.essential_description': 'These cookies are essential for the basic functionality of the website and cannot be disabled.',
    'cookie_consent.analytics': 'Analytics Cookies',
    'cookie_consent.analytics_description': 'These cookies help us understand how visitors interact with the website by collecting and reporting information anonymously.',
    'cookie_consent.marketing': 'Marketing Cookies',
    'cookie_consent.marketing_description': 'These cookies are used to track visitors across websites. The intention is to display ads that are relevant and engaging for the individual user.',
    'cookie_consent.save_preferences': 'Save Preferences',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Detect browser language with 'de' as fallback
  const detectLanguage = (): Language => {
    const stored = localStorage.getItem('pflegeflix-language');
    if (stored && (stored === 'de' || stored === 'en')) {
      return stored as Language;
    }
    
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('de') ? 'de' : 'de'; // Default to 'de'
  };

  const [language, setLanguageState] = useState<Language>(detectLanguage);

  // Update html lang attribute and persist choice
  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('pflegeflix-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    toast.success(lang === 'de' ? 'Sprache auf Deutsch geändert' : 'Language changed to English');
  };

  // Translation function with interpolation and graceful fallback
  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key];
    
    // Fallback to German if key not found in current language
    if (!translation) {
      translation = translations.de[key];
      if (!translation) {
        console.warn(`Translation missing for key: ${key}`);
        return key; // Show key as last resort
      }
      console.warn(`Translation missing for key "${key}" in ${language}, using German fallback`);
    }

    // Handle interpolation
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(`{${paramKey}}`, String(value));
      });
    }

    return translation;
  };

  // Format numbers according to locale
  const formatNumber = (num: number): string => {
    return new Intl.NumberFormat(language === 'de' ? 'de-DE' : 'en-US').format(num);
  };

  // Format currency with localized unit labels
  const formatCurrency = (amount: number, unit: '€/h' | '€/Monat' = '€/Monat'): string => {
    const formatted = new Intl.NumberFormat(language === 'de' ? 'de-DE' : 'en-US', {
      style: 'currency',
      currency: 'EUR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);

    // Localize unit label
    const unitLabel = unit === '€/h' 
      ? (language === 'de' ? '/Std' : '/hr')
      : (language === 'de' ? '/Monat' : '/month');

    return `${formatted}${unitLabel}`;
  };

  // Format dates according to locale
  const formatDate = (date: Date | string, format: 'short' | 'long' = 'short'): string => {
    const dateObj = typeof date === 'string' ? new Date(date) : date;
    
    if (format === 'long') {
      return new Intl.DateTimeFormat(language === 'de' ? 'de-DE' : 'en-US', {
        dateStyle: 'long',
      }).format(dateObj);
    }
    
    return new Intl.DateTimeFormat(language === 'de' ? 'de-DE' : 'en-US', {
      dateStyle: 'short',
    }).format(dateObj);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatNumber, formatCurrency, formatDate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};